---
name: "EDL Creator"
guid: "6B0E323A-4AEE-4B10-813F-1E060488AE90"
version: "0.3.0.0"
targetAbi: "10.10.0.0"
framework: "net8.0"
overview: "Create .edl files from Media Segments"
description: >
  These files can be used by Kodi and other players
   to skip content like commercials and are stored next to your media. Therefore you need write access.
category: "General"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.Edl.dll"
changelog: >
  changelog
